server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
      username: ${db.username}
      password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
    ddlAuto: create

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true